invoice_entity.settings:
  type: mapping
  label: Variable Settings of My Module
  mapping:
   invoice_number:
     type: string
   secure_code:
     type: string
   consecutive_code:
     type: string