v: 2.6.0
overrideConfig: false
ie:
  - DS_Store
  - less
  - scss
id:
  - scss
  - .svn
  - .sass-cache
cleanPublic: 'true'
patternStates:
  - inprogress
  - inreview
  - complete
styleGuideExcludes: ''
cacheBusterOn: 'true'
exportDir: export
publicDir: public
sourceDir: ../source
defaultPattern: all
defaultShowPatternInfo: false
ishMinimum: '240'
ishMaximum: '2600'
ishControlsHide:
  - hay
lineageMatch: >-
  {%([ ]+)?include(
  |\()[&quot;\&#039;]([A-Za-z0-9-_]+)[&quot;\&#039;](\))?(.*)%}
lineageMatchKey: 3
patternExtension: twig
twigDebug: true
twigAutoescape: false
twigDefaultDateFormat: ''
twigDefaultIntervalFormat: ''
twigMacroExt: macro.twig
twigFilterExt: filter.php
twigFunctionExt: function.php
twigTagExt: tag.php
twigTestExt: test.php
styleguideKit: pattern-lab/styleguidekit-twig-default
styleguideKitPath: vendor/pattern-lab/styleguidekit-twig-default
plugins:
  faker:
    enabled: true
    locale: en_US
  twigNamespaces:
    enabled: true
    namespaces:
      svgs:
        paths:
          - ../images/svgs
      base:
        paths:
          - ../source/_patterns/00-base
          - ../source/_patterns/00-base/05-colors
          - ../source/_patterns/00-base/10-spacing
          - ../source/_patterns/00-base/15-typography/fonts
          - ../source/_patterns/00-base/15-typography/headings
          - ../source/_patterns/00-base/15-typography/lists
          - ../source/_patterns/00-base/15-typography/text
          - ../source/_patterns/00-base/animations/01-transitions
          - ../source/_patterns/00-base/breakpoints
          - ../source/_patterns/00-base/grids
          - ../source/_patterns/00-base/utilities/borders
      atoms:
        paths:
          - ../source/_patterns/01-atoms
          - ../source/_patterns/01-atoms/buttons
          - ../source/_patterns/01-atoms/form-elements/checkbox
          - ../source/_patterns/01-atoms/form-elements/date
          - ../source/_patterns/01-atoms/form-elements/fieldset
          - ../source/_patterns/01-atoms/form-elements/input-disabled
          - ../source/_patterns/01-atoms/form-elements/input-file
          - ../source/_patterns/01-atoms/form-elements/input-text
          - ../source/_patterns/01-atoms/form-elements/radio
          - ../source/_patterns/01-atoms/form-elements/select
          - ../source/_patterns/01-atoms/form-elements/textarea-disabled
          - ../source/_patterns/01-atoms/form-elements/textarea
          - ../source/_patterns/01-atoms/images
          - ../source/_patterns/01-atoms/tables
      molecules:
        paths:
          - ../source/_patterns/02-molecules
          - ../source/_patterns/02-molecules/adv-forms/search
          - ../source/_patterns/02-molecules/branding
          - ../source/_patterns/02-molecules/breadcrumbs
          - ../source/_patterns/02-molecules/caption-block
          - ../source/_patterns/02-molecules/nav-local-task
          - ../source/_patterns/02-molecules/status-msgs
      organisms:
        paths:
          - ../source/_patterns/03-organisms
          - ../source/_patterns/03-organisms/grids/accordion
          - ../source/_patterns/03-organisms/grids/caption-grid-block
          - ../source/_patterns/03-organisms/grids/collapsible-block
          - ../source/_patterns/03-organisms/grids/products
          - ../source/_patterns/03-organisms/site/site-footer
          - ../source/_patterns/03-organisms/site/site-header
      templates:
        paths:
          - ../source/_patterns/04-templates
          - ../source/_patterns/04-templates/00-site
          - ../source/_patterns/04-templates/content-types
          - ../source/_patterns/04-templates/content-types/cotizacion/content
      pages:
        paths:
          - ../source/_patterns/05-pages
